# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create folder
      run: |
        mkdir aareguru

    - name: GoReleaser Action
      uses: goreleaser/goreleaser-action@v6.3.0
      with:
        args: release --snapshot
        workdir: aareguru
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: aareguru
        path: aareguru/dist/*
